### PR TITLE
Generalizing the submodels framework for allowing multiple (sub-)parameters

### PR DESCRIPTION
**Pull request by franzbischoff**
The use-case here is this model:

[FLOSS](https://github.com/franzbischoff/false.alarm/blob/feature/newfeature2sm/R/floss_model.R)

This model is still a concept but serves as an example of future models that may need/feature more than one sub-arguments.
The time-consuming work is made with the first parameters, and later,                                       `regime_threshold` and `regime_landmark` arguments can be quickly tuned. Then I realized that multi_predict only accepts one argument for submodels.

This PR allows the arguments marked as `has_submodel` to be quickly tuned altogether.

### CODE REVIEW

**Comment by franzbischoff** [comment]
I tried to run the check on my fork and `r-lib/actions/setup-r-dependencies@v2` fails the same way...

**Comment by EmilHvitfeldt** [comment]
I reran that check and it runs clean now

**Comment by topepo** [comment]
I'm really interested in getting this into tune. However, it will require a lot of focus time for me to look at the changes. 

We're in the process of getting new versions of almost all of our packages on CRAN prior to our big conference at the end of July. I'll try to look at this in 2 weeks but it may have to wait until August.

**Comment by franzbischoff** [comment]
I see I forgot to mention about this function (I didn't add it into the PR because it is customized for my model, but may serve as an example for using the multiple (sub-)parameters using tune_grid (and not multi_predict directly):

```R
min_grid.floss_regime_model <- function(x, grid, ...) {
  ## This is basically `fit_max_value()` with an extras
  gr_nms <- names(grid)
  param_info <- tune:::get_submodel_info(x)
  sub_nm <- param_info$id[param_info$has_submodel]

  if (length(sub_nm) == 0 | !any(names(grid) %in% sub_nm)) {
    return(tune:::blank_submodels(grid))
  }

  fixed_args <- gr_nms[!(gr_nms %in% sub_nm)]
  sub_nm <- sub_nm[(sub_nm %in% gr_nms)] # remove unnused submodels

  if (length(fixed_args) == 0) {
    if (length(sub_nm) > 1) {
      res <- tune:::submod_only_multi(grid)
    } else {
      res <- tune:::submod_only(grid)
    }
  } else {
    if (length(sub_nm) > 1) {
      res <- tune:::submod_and_others_multi(grid, fixed_args)
    } else {
      res <- tune:::submod_and_others(grid, fixed_args)
    }
  }
  res
}
```

**Comment by simonpcouch** [comment]
As this hasn't come to the top of our to-do list in the last 1.5 years, I'm going to go ahead and close. Thank you for effort here!

This issue will continue to be indexed in search, so if more folks come through in the future and upvote, we'll see that this ought to be higher-priority and reopen.

**Pull request closed without merging**
