### PR TITLE
Test units for multi_predict

### PR DESCRIPTION
**Pull request by franzbischoff**
Related to Issue https://github.com/tidymodels/tune/issues/500

This PR adds two unit tests for the `multi_predict` function.

### CODE REVIEW

**Comment by juliasilge** [comment]
Can you give us a bit more background for your thoughts on adding these tests here? The tests for `multi_predict` and its methods [are in parsnip](https://github.com/tidymodels/parsnip/search?q=multi_predict).

**Comment by franzbischoff** [comment]
Well, that is an example of looking "too near" from the tree. 😄 
Since I was focusing on the `tune` package I didn't realize that `parsnip` had that covered.
What brought me to adding such test in `tune` however was the fact that there is a `test-predict.R` here on `tune` and I missed the `multi_predict` since it also can be used for _tuning_ purposes.

I'll review this in `parsnip` and I'll get back here later. Maybe the _tuning_ process using `multi_predict` is the only suitable part here.

Thanks.

**Comment by juliasilge** [comment]
Can you tell me a bit more about what you want to test here that is not already [tested in extratests](https://github.com/tidymodels/extratests/blob/main/tests/testthat/test-engine-parameters-c5.R)? We've got multiple trees already in those tests.

**Comment by franzbischoff** [comment]
Right! Well, I think this solves this PR.
Sorry to make you dig into this!
I'll be more careful next time.

Best regards!

**Pull request closed without merging**
