### PR TITLE
Best practices and new tests

### PR DESCRIPTION
**Pull request by franzbischoff**
Suggestions:

- `dplyr::one_of` was superseded by `dplyr::all_of`
- Added namespaces on several external packages usage
- Removed unnecessary namespaces on test which causes incompatibility with VSCode Testing suits and no harm with RStudio.
- Added #nolint statements where `lintr` complains about not using `snake_case` format.
- Added 2 unit tests for `multi_predict`

### CODE REVIEW

**Comment by juliasilge** [comment]
Thank you so much for this PR @franzbischoff!

This still does a lot in one PR 🙈 (you may be feeling annoyed right now) so would you mind breaking it up more?

For example, `dplyr::all_of` we for sure will just merge in right away but we probably will not add the `#nolint ` change.

> Added namespaces on several external packages usage
Can you share why you have added this? Have you run into a problem?

> Removed unnecessary namespaces on test which causes incompatibility with VSCode Testing suits and no harm with RStudio.
Can you say a little more about this? This is the functions that were previously unexported like `tune::check_workflow()`?

**Comment by simonpcouch** [comment]
Thanks again for the PR, @franzbischoff.

> Do I need to split the PR into more PRs?

I would indeed follow Julia's recommendations to move this PR closer to merging!

* We're on board for the `dplyr::all_of` changes. Those can live in a standalone PR, and do not need the reference to our team's documentation.
* We're on board for transitioning `:::` to `::` (or no namespacing) with newly exported functions! Those can also live in a standalone PR.
* We'll refrain from merging the lintr comments for the reasons you note. This seems like a lintr issue rather than one with our tooling.
* Julia is [quite familiar](https://www.tmwr.org/) with namespacing and good practices for modeling packages. We feel good about our current approach to namespacing, so no worries on filing another PR there!

If there are other features in this PR that you'd like to see merged, we'll ask that you file them in separate PRs, each with their own [reprex](https://github.com/tidyverse/reprex#what-is-a-reprex) (reproducible example) demonstrating the issues you're encountering/solving. Much appreciated!

**Comment by franzbischoff** [comment]
Hello @simonpcouch!

What I understand from your comments are:

- The `dplyr::all_of` changes are ok, but is it better to move them to a single PR? Should I go forward with it?
- The `:::` to `::` changes are ok and also must be moved to another PR?

I sincerely apologize if I may have expressed myself wrong (I'm not an English native speaker). I'm far from having any intention to "explain" any 'good practice' for your team. I'm just justifying myself for my suggestions. I really apologize!

If you think it is better I'll close this PR and continue our conversation on the Issues panel, and when we feel we are ok I re-open small PRs with narrow scopes and better feedback from you.

Best regards

**Comment by franzbischoff** [comment]
Thanks!

**Pull request closed without merging**
