### PR TITLE
Account for submodels in setting `.config`

### LINKED ISSUE #233: .config constant across models
``` r
library(tidymodels)
#> ── Attaching packages ──────────────────────────────────────────────────────────────────────────── tidymodels 0.1.0.9000 ──
#> ✓ broom     0.5.6           ✓ recipes   0.1.12.9000
#> ✓ dials     0.0.7           ✓ rsample   0.0.7      
#> ✓ dplyr     1.0.0           ✓ tibble    3.0.1      
#> ✓ ggplot2   3.3.1           ✓ tune      0.1.0.9000 
#> ✓ infer     0.5.1           ✓ workflows 0.1.1      
#> ✓ parsnip   0.1.1.9000      ✓ yardstick 0.0.6      
#> ✓ purrr     0.3.4
#> ── Conflicts ──────────────────────────────────────────────────────────────────────────────────── tidymodels_conflicts() ──
#> x purrr::discard() masks scales::discard()
#> x dplyr::filter()  masks stats::filter()
#> x dplyr::lag()     masks stats::lag()
#> x recipes::step()  masks stats::step()
library(tidyr)
options(width = 110)

data(two_class_dat, package = "modeldata")

set.seed(283)
rs <- bootstraps(two_class_dat, times = 100)

mod <-
  nearest_neighbor(neighbors = tune(), dist_power = tune(), weight_func = tune()) %>%
  set_engine("kknn") %>%
  set_mode("classification")

initial_grid <- crossing(neighbors = 1:3, dist_power = 1, weight_func = "rank")

set.seed(33)
res <-
  mod %>%
  tune_grid(Class ~ ., resamples = rs, grid = initial_grid, metrics = metric_set(roc_auc))

collect_metrics(res)
#> # A tibble: 3 x 9
#>   neighbors weight_func dist_power .metric .estimator  mean     n std_err .config
#>       <int> <chr>            <dbl> <chr>   <chr>      <dbl> <int>   <dbl> <chr>  
#> 1         1 rank                 1 roc_auc binary     0.735   100 0.00223 Model1 
#> 2         2 rank                 1 roc_auc binary     0.770   100 0.00208 Model1 
#> 3         3 rank                 1 roc_auc binary     0.797   100 0.00205 Model1
```

<sup>Created on 2020-06-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This probably has to do with `neighbors` being a parameter that can use sub-models.

### PR DESCRIPTION
**Pull request by juliasilge**
This PR closes #233. When the internal ID `.config` is set, now we check for submodels. I mostly checked this by looking at:

https://github.com/tidymodels/tune/blob/4bbbae913d44bb78bf94d66092366a914f7fbb03/R/grid_code_paths.R#L93

and taking the `length()` of that vector. This works for the models I checked and the tests pass, but are there are other models with submodels we can check out here to see how this performs?

Here are some example results now:

``` r
library(tidymodels)
#> ── Attaching packages ───────────────────────────────────────────────────────────────────── tidymodels 0.1.0 ──
#> ✓ broom     0.5.6          ✓ recipes   0.1.12    
#> ✓ dials     0.0.7          ✓ rsample   0.0.7     
#> ✓ dplyr     1.0.0          ✓ tibble    3.0.1     
#> ✓ ggplot2   3.3.2          ✓ tune      0.1.0.9000
#> ✓ infer     0.5.2          ✓ workflows 0.1.1     
#> ✓ parsnip   0.1.1          ✓ yardstick 0.0.6     
#> ✓ purrr     0.3.4
#> ── Conflicts ──────────────────────────────────────────────────────────────────────── tidymodels_conflicts() ──
#> x purrr::discard() masks scales::discard()
#> x dplyr::filter()  masks stats::filter()
#> x dplyr::lag()     masks stats::lag()
#> x recipes::step()  masks stats::step()
library(dplyr)
library(tidyr)

data(two_class_dat, package = "modeldata")

set.seed(283)
rs <- bootstraps(two_class_dat, times = 10)

mod <-
  nearest_neighbor(neighbors = tune(), dist_power = tune(), weight_func = tune()) %>%
  set_engine("kknn") %>%
  set_mode("classification")

mod_grid <- crossing(neighbors = 1:3, dist_power = 1:2, weight_func = "rank")

set.seed(33)
tune_mod_with_form_res <-
  mod %>%
  tune_grid(Class ~ ., resamples = rs, grid = mod_grid, metrics = metric_set(roc_auc), control = control_grid(save_pred = TRUE))

collect_metrics(tune_mod_with_form_res) %>%
  count(neighbors, dist_power, .config)
#> Using `n` as weighting variable
#> ℹ Quiet this message with `wt = n` or count rows with `wt = 1`
#> # A tibble: 6 x 4
#>   neighbors dist_power .config     n
#>       <int>      <int> <chr>   <int>
#> 1         1          1 Model1     10
#> 2         1          2 Model4     10
#> 3         2          1 Model2     10
#> 4         2          2 Model5     10
#> 5         3          1 Model3     10
#> 6         3          2 Model6     10
collect_predictions(tune_mod_with_form_res) %>%
  count(.config)
#> # A tibble: 6 x 2
#>   .config     n
#>   <chr>   <int>
#> 1 Model1   2898
#> 2 Model2   2898
#> 3 Model3   2898
#> 4 Model4   2898
#> 5 Model5   2898
#> 6 Model6   2898
```

<sup>Created on 2020-06-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
**Six** models, for the combinations of `neighbors` and `dist_power`. ✅

There are similar results for tuning a model with a recipe. Here are results for tuning a model and recipe at the same time:
``` r
library(tidymodels)
#> ── Attaching packages ───────────────────────────────────────────────────────────────────── tidymodels 0.1.0 ──
#> ✓ broom     0.5.6          ✓ recipes   0.1.12    
#> ✓ dials     0.0.7          ✓ rsample   0.0.7     
#> ✓ dplyr     1.0.0          ✓ tibble    3.0.1     
#> ✓ ggplot2   3.3.2          ✓ tune      0.1.0.9000
#> ✓ infer     0.5.2          ✓ workflows 0.1.1     
#> ✓ parsnip   0.1.1          ✓ yardstick 0.0.6     
#> ✓ purrr     0.3.4
#> ── Conflicts ──────────────────────────────────────────────────────────────────────── tidymodels_conflicts() ──
#> x purrr::discard() masks scales::discard()
#> x dplyr::filter()  masks stats::filter()
#> x dplyr::lag()     masks stats::lag()
#> x recipes::step()  masks stats::step()
library(dplyr)
library(tidyr)

set.seed(6735)
folds <- vfold_cv(mtcars, v = 5)

spline_rec <-
  recipe(mpg ~ ., data = mtcars) %>%
  step_ns(disp, deg_free = tune("disp")) %>%
  step_ns(wt, deg_free = tune("wt"))

mod <-
  nearest_neighbor(neighbors = tune(), dist_power = tune(), weight_func = tune()) %>%
  set_engine("kknn") %>%
  set_mode("regression")

lots_o_grid <- crossing(disp = 2:5, wt = 2:5, neighbors = 1:3, dist_power = 1:2, weight_func = "rank")

# Warnings will occur from making spline terms on the holdout data that are
# extrapolations.
spline_res1 <-
  tune_grid(mod, spline_rec, resamples = folds, grid = lots_o_grid, control = control_grid(save_pred = TRUE))

collect_metrics(spline_res1)
#> # A tibble: 192 x 11
#>    neighbors weight_func dist_power  disp    wt .metric .estimator  mean     n
#>        <int> <chr>            <int> <int> <int> <chr>   <chr>      <dbl> <int>
#>  1         1 rank                 1     2     2 rmse    standard   2.89      5
#>  2         1 rank                 1     2     2 rsq     standard   0.780     5
#>  3         2 rank                 1     2     2 rmse    standard   2.21      5
#>  4         2 rank                 1     2     2 rsq     standard   0.795     5
#>  5         3 rank                 1     2     2 rmse    standard   2.32      5
#>  6         3 rank                 1     2     2 rsq     standard   0.797     5
#>  7         1 rank                 2     2     2 rmse    standard   3.16      5
#>  8         1 rank                 2     2     2 rsq     standard   0.740     5
#>  9         2 rank                 2     2     2 rmse    standard   2.42      5
#> 10         2 rank                 2     2     2 rsq     standard   0.813     5
#> # … with 182 more rows, and 2 more variables: std_err <dbl>, .config <chr>
collect_predictions(spline_res1) %>%
  count(.config)
#> # A tibble: 96 x 2
#>    .config             n
#>    <chr>           <int>
#>  1 Recipe1_Model1     32
#>  2 Recipe1_Model2     32
#>  3 Recipe1_Model3     32
#>  4 Recipe1_Model4     32
#>  5 Recipe1_Model5     32
#>  6 Recipe1_Model6     32
#>  7 Recipe10_Model1    32
#>  8 Recipe10_Model2    32
#>  9 Recipe10_Model3    32
#> 10 Recipe10_Model4    32
#> # … with 86 more rows
```

<sup>Created on 2020-06-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

So as expected, 16 recipes and 6 models.

Tuning with no submodels behaves as before because `length(NULL)` (for no submodel parameters) is equal to zero.

### CODE REVIEW

**Comment by juliasilge** [comment]
I went through all the `_data.R` model files in parsnip and it looks like there are no models with more than one `has_submodel = TRUE` arguments for now, so this PR should work with all models for now. This may need to be revisited in the future for models that have more than one `has_submodel = TRUE` argument. (My current best guess at such a step would be to factor out handling `param_val$.submodels` into a little function.)

Here are results for another model with submodels:

``` r
library(tidymodels)
#> ── Attaching packages ───────────────────────────────────────────────────────────────────── tidymodels 0.1.0 ──
#> ✓ broom     0.5.6          ✓ recipes   0.1.12    
#> ✓ dials     0.0.7          ✓ rsample   0.0.7     
#> ✓ dplyr     1.0.0          ✓ tibble    3.0.1     
#> ✓ ggplot2   3.3.2          ✓ tune      0.1.0.9000
#> ✓ infer     0.5.2          ✓ workflows 0.1.1     
#> ✓ parsnip   0.1.1          ✓ yardstick 0.0.6     
#> ✓ purrr     0.3.4
#> ── Conflicts ──────────────────────────────────────────────────────────────────────── tidymodels_conflicts() ──
#> x purrr::discard() masks scales::discard()
#> x dplyr::filter()  masks stats::filter()
#> x dplyr::lag()     masks stats::lag()
#> x recipes::step()  masks stats::step()
library(dplyr)
library(tidyr)

data(two_class_dat, package = "modeldata")

set.seed(283)
rs <- bootstraps(two_class_dat, times = 10)

mod <-
  boost_tree(trees = tune(), mtry = tune(), min_n = tune()) %>%
  set_engine("xgboost") %>%
  set_mode("classification")


mod_grid <- crossing(trees = c(100, 1000, 5000), mtry = 1:3, min_n = c(5, 10, 20))

set.seed(33)
tune_mod_with_form_res <-
  mod %>%
  tune_grid(Class ~ ., resamples = rs, grid = mod_grid, metrics = metric_set(roc_auc), control = control_grid(save_pred = TRUE))
#> i Creating pre-processing data to finalize unknown parameter: mtry

collect_metrics(tune_mod_with_form_res) %>%
  count(trees, mtry, min_n, .config)
#> Using `n` as weighting variable
#> ℹ Quiet this message with `wt = n` or count rows with `wt = 1`
#> # A tibble: 27 x 5
#>    trees  mtry min_n .config     n
#>    <dbl> <int> <dbl> <chr>   <int>
#>  1   100     1     5 Model1     10
#>  2   100     1    10 Model4     10
#>  3   100     1    20 Model7     10
#>  4   100     2     5 Model10    10
#>  5   100     2    10 Model13    10
#>  6   100     2    20 Model16    10
#>  7   100     3     5 Model19    10
#>  8   100     3    10 Model22    10
#>  9   100     3    20 Model25    10
#> 10  1000     1     5 Model2     10
#> # … with 17 more rows
collect_predictions(tune_mod_with_form_res) %>%
  count(.config)
#> # A tibble: 27 x 2
#>    .config     n
#>    <chr>   <int>
#>  1 Model1   2898
#>  2 Model10  2898
#>  3 Model11  2898
#>  4 Model12  2898
#>  5 Model13  2898
#>  6 Model14  2898
#>  7 Model15  2898
#>  8 Model16  2898
#>  9 Model17  2898
#> 10 Model18  2898
#> # … with 17 more rows
```

<sup>Created on 2020-06-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
It works correctly to set up a separate internal ID across submodels.

**Comment by topepo** [comment]
Can you regenerate the test objects? See `inst/examples/test_objects.R` and `inst/examples/ames_knn.R`

**Comment by juliasilge** [comment]
I changed `append_extracts()` so that it works like the other `append_` functions with respect to the `.config` argument (so it can handle submodels) and updated the test objects. 👍

**Comment by juliasilge** [comment]
The names we give the internal model/recipe configuration IDs are now more harmonized. Here is an example:

``` r
library(tidymodels)
#> ── Attaching packages ────────────────────────────────────────────── tidymodels 0.1.0 ──
#> ✓ broom     0.5.6          ✓ recipes   0.1.13    
#> ✓ dials     0.0.7.9000     ✓ rsample   0.0.7     
#> ✓ dplyr     1.0.0          ✓ tibble    3.0.1     
#> ✓ ggplot2   3.3.2          ✓ tune      0.1.0.9000
#> ✓ infer     0.5.2          ✓ workflows 0.1.1.9000
#> ✓ parsnip   0.1.1.9000     ✓ yardstick 0.0.6     
#> ✓ purrr     0.3.4
#> ── Conflicts ───────────────────────────────────────────────── tidymodels_conflicts() ──
#> x purrr::discard() masks scales::discard()
#> x dplyr::filter()  masks stats::filter()
#> x dplyr::lag()     masks stats::lag()
#> x recipes::step()  masks stats::step()
library(dplyr)
library(tidyr)

data(two_class_dat, package = "modeldata")

set.seed(283)
rs <- bootstraps(two_class_dat, times = 10)

mod <-
  boost_tree(trees = tune(), mtry = tune(), min_n = tune()) %>%
  set_engine("xgboost") %>%
  set_mode("classification")


mod_grid <- crossing(trees = c(100, 1000, 5000), mtry = 1:3, min_n = c(5, 10, 20))

set.seed(33)
tune_mod_with_form_res <-
  mod %>%
  tune_grid(Class ~ ., resamples = rs, grid = mod_grid, metrics = metric_set(roc_auc), control = control_grid(save_pred = TRUE))

collect_metrics(tune_mod_with_form_res) %>%
  count(trees, mtry, min_n, .config)
#> Using `n` as weighting variable
#> ℹ Quiet this message with `wt = n` or count rows with `wt = 1`
#> # A tibble: 27 x 5
#>    trees  mtry min_n .config     n
#>    <dbl> <int> <dbl> <chr>   <int>
#>  1   100     1     5 Model01    10
#>  2   100     1    10 Model04    10
#>  3   100     1    20 Model07    10
#>  4   100     2     5 Model10    10
#>  5   100     2    10 Model13    10
#>  6   100     2    20 Model16    10
#>  7   100     3     5 Model19    10
#>  8   100     3    10 Model22    10
#>  9   100     3    20 Model25    10
#> 10  1000     1     5 Model02    10
#> # … with 17 more rows
collect_predictions(tune_mod_with_form_res) %>%
  count(.config)
#> # A tibble: 27 x 2
#>    .config     n
#>    <chr>   <int>
#>  1 Model01  2898
#>  2 Model02  2898
#>  3 Model03  2898
#>  4 Model04  2898
#>  5 Model05  2898
#>  6 Model06  2898
#>  7 Model07  2898
#>  8 Model08  2898
#>  9 Model09  2898
#> 10 Model10  2898
#> # … with 17 more rows
```

<sup>Created on 2020-07-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

I believe these latest commits handle all the appropriate combinations of recipes + models.

**Pull request merged**
